In [9]:

import numpy as np, pandas as pd

#Loading train and test dataset
x_train = np.load('E:/DataScience/X_kannada_MNIST_train.npz')['arr_0']
x_test = np.load('E:/DataScience/X_kannada_MNIST_test.npz')['arr_0']
y_train = np.load('E:/DataScience/y_kannada_MNIST_train.npz')['arr_0']
y_test = np.load('E:/DataScience/y_kannada_MNIST_test.npz')['arr_0']

print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(60000, 28, 28) (10000, 28, 28)
(60000,) (10000,)


In [10]:
from sklearn.decomposition import PCA

x_train_flat = x_train.reshape(x_train.shape[0], -1)
x_test_flat = x_test.reshape(x_test.shape[0], -1)

n_components = 10
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

(10000, 10)
(60000, 10)


In [15]:
#KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix

model=KNeighborsClassifier(n_neighbors=2)
model.fit(x_train_pca,y_train)
train_pred = model.predict(x_train_pca)
test_pred = model.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

*****KNeighborsClassifier
Train Precision: 0.9783
Train Recall: 0.9783
Train F1 Score: 0.9783
Confusion Matrix:
[[836 125   0  21   2   0   2   2   8   4]
 [ 71 901   0  13   3   1   0   2   7   2]
 [  6   1 979   4   0   7   1   1   0   1]
 [ 18  18   1 877  28  20   3  16  13   6]
 [  0   4   0  28 942  17   0   2   5   2]
 [  0   9   1  19 149 814   2   1   3   2]
 [  0   7   1  50  16  11 855  48   1  11]
 [ 10  11   2  82  35   4 203 632   4  17]
 [ 33  19   2   3   5   4   1   1 927   5]
 [ 13  23   0   5  36   3   9   3  29 879]]
Test Data
Test Precision: 0.8642
Test Recall: 0.8642
Test F1 Score: 0.8642
Confusion Matrix:
[[836 125   0  21   2   0   2   2   8   4]
 [ 71 901   0  13   3   1   0   2   7   2]
 [  6   1 979   4   0   7   1   1   0   1]
 [ 18  18   1 877  28  20   3  16  13   6]
 [  0   4   0  28 942  17   0   2   5   2]
 [  0   9   1  19 149 814   2   1   3   2]
 [  0   7   1  50  16  11 855  48   1  11]
 [ 10  11   2  82  35   4 203 632   4  17]
 [ 33  19   2   3   

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix

model=DecisionTreeClassifier(criterion="entropy",max_depth=3,min_samples_split=10)
model.fit(x_train_pca,y_train)
train_pred = model.predict(x_train_pca)
test_pred = model.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

*****DecisionTreeClassifier
Train Precision: 0.5447833333333333
Train Recall: 0.5447833333333333
Train F1 Score: 0.5447833333333333
Confusion Matrix:
[[  0 677   2  20  19   0   2   6 246  28]
 [  0 625   0  40   6   0   0   0 100 229]
 [  0   5 229  14  12   0  52   0 265 423]
 [  0  15  21 741  29   0  65  54  59  16]
 [  0   6   0 233 643   0   0   4 102  12]
 [  0   8   0  54 292   0  22   0 570  54]
 [  0  19   1 102   2   0 682  54  97  43]
 [  0  54  12 143 104   0 343 306  29   9]
 [  0 115   3   2   2   0  18   0 856   4]
 [  0 267   0  16  33   0   0   8 150 526]]
Test Data
Test Precision: 0.4608
Test Recall: 0.4608
Test F1 Score: 0.4608
Confusion Matrix:
[[  0 677   2  20  19   0   2   6 246  28]
 [  0 625   0  40   6   0   0   0 100 229]
 [  0   5 229  14  12   0  52   0 265 423]
 [  0  15  21 741  29   0  65  54  59  16]
 [  0   6   0 233 643   0   0   4 102  12]
 [  0   8   0  54 292   0  22   0 570  54]
 [  0  19   1 102   2   0 682  54  97  43]
 [  0  54  12 143 104   0

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix

model=RandomForestClassifier()
model.fit(x_train_pca,y_train)
train_pred = model.predict(x_train_pca)
test_pred = model.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

*****RandomForestClassifier
Train Precision: 1.0
Train Recall: 1.0
Train F1 Score: 1.0
Confusion Matrix:
[[780 148   3  30   5   0   3   4  19   8]
 [ 33 910   1  19   7   2   0   4  15   9]
 [  4   1 981   1   0   8   0   3   1   1]
 [ 10   8   2 887  16  20   7  32  16   2]
 [  0   2   0  26 925  33   0   2   7   5]
 [  0   3   2   9 123 846   3   2   8   4]
 [  2  10   2  53  10  27 832  47   2  15]
 [  3  11   1  40  24   0 135 741  12  33]
 [ 14  14   2   3   3   6   1   0 954   3]
 [  6  10   0   4  18   0   5   3  54 900]]
Test Data
Test Precision: 0.8756
Test Recall: 0.8756
Test F1 Score: 0.8756
Confusion Matrix:
[[780 148   3  30   5   0   3   4  19   8]
 [ 33 910   1  19   7   2   0   4  15   9]
 [  4   1 981   1   0   8   0   3   1   1]
 [ 10   8   2 887  16  20   7  32  16   2]
 [  0   2   0  26 925  33   0   2   7   5]
 [  0   3   2   9 123 846   3   2   8   4]
 [  2  10   2  53  10  27 832  47   2  15]
 [  3  11   1  40  24   0 135 741  12  33]
 [ 14  14   2   3   3   6  

In [19]:
from sklearn.svm import SVC
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix

model=SVC()
model.fit(x_train_pca,y_train)
train_pred = model.predict(x_train_pca)
test_pred = model.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

*****SVC
Train Precision: 0.96535
Train Recall: 0.96535
Train F1 Score: 0.96535
Confusion Matrix:
[[810 140   1  22   6   0   1   2  15   3]
 [ 19 924   0  27   3   3   0   4  12   8]
 [  3   2 984   1   0   5   0   3   1   1]
 [  8  11   0 887  20  22   8  26  18   0]
 [  0   1   0  14 948  22   0   0   5  10]
 [  0   4   1   4 124 854   3   3   4   3]
 [  0  10   1  50  20  21 845  40   0  13]
 [  6  13   0  33  17   4 135 747   7  38]
 [  8  14   4   0   4   4   3   0 959   4]
 [  2  13   0   0  23   0   6   3  41 912]]
Test Data
Test Precision: 0.887
Test Recall: 0.887
Test F1 Score: 0.887
Confusion Matrix:
[[810 140   1  22   6   0   1   2  15   3]
 [ 19 924   0  27   3   3   0   4  12   8]
 [  3   2 984   1   0   5   0   3   1   1]
 [  8  11   0 887  20  22   8  26  18   0]
 [  0   1   0  14 948  22   0   0   5  10]
 [  0   4   1   4 124 854   3   3   4   3]
 [  0  10   1  50  20  21 845  40   0  13]
 [  6  13   0  33  17   4 135 747   7  38]
 [  8  14   4   0   4   4   3   0 959

In [22]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

p = Pipeline([('Normalizing',MinMaxScaler()),('MultinomialNB',MultinomialNB())])
p.fit(x_train_pca,y_train) 

train_pred = p.predict(x_train_pca)
test_pred = p.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

*****MultinomialNB
Train Precision: 0.7998166666666666
Train Recall: 0.7998166666666666
Train F1 Score: 0.7998166666666666
Confusion Matrix:
[[509 254  13 175   2   3   2  12  26   4]
 [ 40 654  18 229   4  12   0   0  30  13]
 [  3   4 905  26  11  34   1   5   1  10]
 [  5   3   2 784  91  26  13  75   1   0]
 [  0   1   2 155 733  96   5   0   5   3]
 [  0   1  28  85 203 648  15  11   7   2]
 [  2   5  22  50  62  31 703 109   9   7]
 [  1  14   4 282  23   3 164 509   0   0]
 [ 85  73  31  26   2   5  10   1 745  22]
 [  7  88   1 132  18   3   7   7  64 673]]
Test Data
Test Precision: 0.6863
Test Recall: 0.6863
Test F1 Score: 0.6863
Confusion Matrix:
[[509 254  13 175   2   3   2  12  26   4]
 [ 40 654  18 229   4  12   0   0  30  13]
 [  3   4 905  26  11  34   1   5   1  10]
 [  5   3   2 784  91  26  13  75   1   0]
 [  0   1   2 155 733  96   5   0   5   3]
 [  0   1  28  85 203 648  15  11   7   2]
 [  2   5  22  50  62  31 703 109   9   7]
 [  1  14   4 282  23   3 164 509 

In [23]:
n_components = 15
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

models=[ KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),SVC() 
       ]
for model in models:
    model.fit(x_train_pca,y_train)
    train_pred = model.predict(x_train_pca)
    test_pred = model.predict(x_test_pca)
    
    print(f"*****{type(model).__name__}")
    print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
    print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
    print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))
    print("Test Data")
    print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
    print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
    print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))


(10000, 15)
(60000, 15)
*****KNeighborsClassifier
Train Precision: 0.9842166666666666
Train Recall: 0.9842166666666666
Train F1 Score: 0.9842166666666666
Confusion Matrix:
[[800 163   2  13   5   0   1   3  10   3]
 [ 15 964   0   5   3   0   0   1   8   4]
 [  3   1 988   2   0   3   2   0   1   0]
 [ 13  12   0 911  23  22   2  14   2   1]
 [  0   1   0   4 972  12   1   1   3   6]
 [  0   0   0   9  93 892   2   1   1   2]
 [  1   1   0  25  25   8 891  37   0  12]
 [  8   7   0  35  35   4 107 771   3  30]
 [  9   6   1   1   2   4   1   0 973   3]
 [  5   7   0   0  19   4   6   2  23 934]]
Test Data
Test Precision: 0.9096
Test Recall: 0.9096
Test F1 Score: 0.9096
Confusion Matrix:
[[800 163   2  13   5   0   1   3  10   3]
 [ 15 964   0   5   3   0   0   1   8   4]
 [  3   1 988   2   0   3   2   0   1   0]
 [ 13  12   0 911  23  22   2  14   2   1]
 [  0   1   0   4 972  12   1   1   3   6]
 [  0   0   0   9  93 892   2   1   1   2]
 [  1   1   0  25  25   8 891  37   0  12]
 [ 

In [24]:
n_components = 20
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

models=[ KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),SVC() 
       ]
for model in models:
    model.fit(x_train_pca,y_train)
    train_pred = model.predict(x_train_pca)
    test_pred = model.predict(x_test_pca)
    
    print(f"*****{type(model).__name__}")
    print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
    print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
    print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))
    print("Test Data")
    print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
    print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
    print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))


(10000, 20)
(60000, 20)
*****KNeighborsClassifier
Train Precision: 0.9870166666666667
Train Recall: 0.9870166666666667
Train F1 Score: 0.9870166666666667
Confusion Matrix:
[[818 148   1  13   7   0   0   1   6   6]
 [ 10 970   0   7   5   0   1   1   4   2]
 [  2   2 989   2   0   2   3   0   0   0]
 [ 12  19   0 918  16  20   1  13   1   0]
 [  0   1   0   6 975   8   2   1   3   4]
 [  0   0   0  11  88 897   2   0   1   1]
 [  2   2   0   7  28   7 920  21   1  12]
 [  7   4   0  31  41   3  80 815   1  18]
 [ 17   7   3   0   3   3   0   0 965   2]
 [  4   6   0   0  12   4  10   2  14 948]]
Test Data
Test Precision: 0.9215
Test Recall: 0.9215
Test F1 Score: 0.9215
Confusion Matrix:
[[818 148   1  13   7   0   0   1   6   6]
 [ 10 970   0   7   5   0   1   1   4   2]
 [  2   2 989   2   0   2   3   0   0   0]
 [ 12  19   0 918  16  20   1  13   1   0]
 [  0   1   0   6 975   8   2   1   3   4]
 [  0   0   0  11  88 897   2   0   1   1]
 [  2   2   0   7  28   7 920  21   1  12]
 [ 

In [25]:
n_components = 25
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

models=[ KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),SVC() 
       ]
for model in models:
    model.fit(x_train_pca,y_train)
    train_pred = model.predict(x_train_pca)
    test_pred = model.predict(x_test_pca)
    
    print(f"*****{type(model).__name__}")
    print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
    print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
    print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))
    print("Test Data")
    print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
    print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
    print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))


(10000, 25)
(60000, 25)
*****KNeighborsClassifier
Train Precision: 0.9883333333333333
Train Recall: 0.9883333333333333
Train F1 Score: 0.9883333333333333
Confusion Matrix:
[[821 152   0   9   5   0   0   0   8   5]
 [  6 978   0   4   5   0   0   0   5   2]
 [  2   1 992   1   0   2   2   0   0   0]
 [  5  17   2 931  14  17   1  12   1   0]
 [  0   1   0   5 981   5   2   1   1   4]
 [  0   0   0   7  79 909   2   0   2   1]
 [  3   2   0  12  25   8 917  21   0  12]
 [  8   1   1  27  38   4  77 826   1  17]
 [ 14   5   1   0   3   2   0   0 972   3]
 [  4   7   0   0  10   3   8   3  12 953]]
Test Data
Test Precision: 0.928
Test Recall: 0.928
Test F1 Score: 0.928
Confusion Matrix:
[[821 152   0   9   5   0   0   0   8   5]
 [  6 978   0   4   5   0   0   0   5   2]
 [  2   1 992   1   0   2   2   0   0   0]
 [  5  17   2 931  14  17   1  12   1   0]
 [  0   1   0   5 981   5   2   1   1   4]
 [  0   0   0   7  79 909   2   0   2   1]
 [  3   2   0  12  25   8 917  21   0  12]
 [  8 

In [26]:
n_components = 30
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

models=[ KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),SVC() 
       ]
for model in models:
    model.fit(x_train_pca,y_train)
    train_pred = model.predict(x_train_pca)
    test_pred = model.predict(x_test_pca)
    
    print(f"*****{type(model).__name__}")
    print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
    print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
    print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))
    print("Test Data")
    print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
    print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
    print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))


(10000, 30)
(60000, 30)
*****KNeighborsClassifier
Train Precision: 0.98935
Train Recall: 0.98935
Train F1 Score: 0.98935
Confusion Matrix:
[[818 156   0   9   5   0   0   2   6   4]
 [  8 980   0   1   5   0   0   0   4   2]
 [  2   1 991   3   0   1   2   0   0   0]
 [  5  15   1 936  14  16   0  13   0   0]
 [  0   1   0   2 985   5   1   2   1   3]
 [  0   0   0   6  80 907   2   1   2   2]
 [  1   1   0   8  21   8 928  22   0  11]
 [ 10   3   0  26  30   2  81 827   1  20]
 [ 14   2   2   0   2   2   0   0 975   3]
 [  3   7   0   0   8   1   6   4   8 963]]
Test Data
Test Precision: 0.931
Test Recall: 0.931
Test F1 Score: 0.931
Confusion Matrix:
[[818 156   0   9   5   0   0   2   6   4]
 [  8 980   0   1   5   0   0   0   4   2]
 [  2   1 991   3   0   1   2   0   0   0]
 [  5  15   1 936  14  16   0  13   0   0]
 [  0   1   0   2 985   5   1   2   1   3]
 [  0   0   0   6  80 907   2   1   2   2]
 [  1   1   0   8  21   8 928  22   0  11]
 [ 10   3   0  26  30   2  81 827   1  

In [27]:
n_components = 15
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

p = Pipeline([('Normalizing',MinMaxScaler()),('MultinomialNB',MultinomialNB())])
p.fit(x_train_pca,y_train) 

train_pred = p.predict(x_train_pca)
test_pred = p.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

(10000, 15)
(60000, 15)
*****SVC
Train Precision: 0.8351833333333334
Train Recall: 0.8351833333333334
Train F1 Score: 0.8351833333333334
Confusion Matrix:
[[536 244  18 135  10   3   4  12  33   5]
 [ 20 689  13 186  29  25   3   0  28   7]
 [  6   3 941  27   3  17   1   1   1   0]
 [  2   6   2 792  60  33  19  86   0   0]
 [  0   1   2 159 763  49   3   2  17   4]
 [  0   2  13  80 189 678  12  15   6   5]
 [  3   4  25  75  18  47 764  57   0   7]
 [  2  13   3 228  28   3 182 541   0   0]
 [133  43  26  26   7   5  14   2 722  22]
 [ 16  28   3 145  14   0  34   1  81 678]]
Test Data
Test Precision: 0.7104
Test Recall: 0.7104
Test F1 Score: 0.7104
Confusion Matrix:
[[536 244  18 135  10   3   4  12  33   5]
 [ 20 689  13 186  29  25   3   0  28   7]
 [  6   3 941  27   3  17   1   1   1   0]
 [  2   6   2 792  60  33  19  86   0   0]
 [  0   1   2 159 763  49   3   2  17   4]
 [  0   2  13  80 189 678  12  15   6   5]
 [  3   4  25  75  18  47 764  57   0   7]
 [  2  13   3 228  2

In [28]:
n_components = 20
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

p = Pipeline([('Normalizing',MinMaxScaler()),('MultinomialNB',MultinomialNB())])
p.fit(x_train_pca,y_train) 

train_pred = p.predict(x_train_pca)
test_pred = p.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

(10000, 20)
(60000, 20)
*****SVC
Train Precision: 0.8524833333333334
Train Recall: 0.8524833333333334
Train F1 Score: 0.8524833333333334
Confusion Matrix:
[[559 251   7 113  14   3   3  10  36   4]
 [ 15 728   5 172  21  26   3   0  22   8]
 [  6   4 946  24   3  14   1   1   1   0]
 [  4   4   3 764  78  32  16  99   0   0]
 [  0   1   0  79 856  25   3   3  26   7]
 [  0   1  11  81 186 671   9  24  14   3]
 [  2   4  12  48  29  57 795  43   0  10]
 [  4   9   3 201  37   3 169 574   0   0]
 [129  31  21  10   7   8  12   2 751  29]
 [ 10  39   1  83  29   0  26   7  85 720]]
Test Data
Test Precision: 0.7364
Test Recall: 0.7364
Test F1 Score: 0.7364
Confusion Matrix:
[[559 251   7 113  14   3   3  10  36   4]
 [ 15 728   5 172  21  26   3   0  22   8]
 [  6   4 946  24   3  14   1   1   1   0]
 [  4   4   3 764  78  32  16  99   0   0]
 [  0   1   0  79 856  25   3   3  26   7]
 [  0   1  11  81 186 671   9  24  14   3]
 [  2   4  12  48  29  57 795  43   0  10]
 [  4   9   3 201  3

In [29]:
n_components = 25
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

p = Pipeline([('Normalizing',MinMaxScaler()),('MultinomialNB',MultinomialNB())])
p.fit(x_train_pca,y_train) 

train_pred = p.predict(x_train_pca)
test_pred = p.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

(10000, 25)
(60000, 25)
*****SVC
Train Precision: 0.8656666666666667
Train Recall: 0.8656666666666667
Train F1 Score: 0.8656666666666667
Confusion Matrix:
[[578 246  10  93  22   2   3  12  32   2]
 [ 11 748   6 157  24  26   1   0  24   3]
 [  7   2 950  19   4  15   1   1   1   0]
 [  4   6   3 762  73  27  15 110   0   0]
 [  0   1   1  55 873  33   4   7  19   7]
 [  0   0  11  28 230 683  11  21  12   4]
 [  2   3   9  39  29  54 806  46   0  12]
 [  6   9   4 129  55   4 169 620   0   4]
 [135  31  15   6   6   8  12   2 758  27]
 [  9  18   0  22  49   0  29  14  92 767]]
Test Data
Test Precision: 0.7545
Test Recall: 0.7545
Test F1 Score: 0.7545
Confusion Matrix:
[[578 246  10  93  22   2   3  12  32   2]
 [ 11 748   6 157  24  26   1   0  24   3]
 [  7   2 950  19   4  15   1   1   1   0]
 [  4   6   3 762  73  27  15 110   0   0]
 [  0   1   1  55 873  33   4   7  19   7]
 [  0   0  11  28 230 683  11  21  12   4]
 [  2   3   9  39  29  54 806  46   0  12]
 [  6   9   4 129  5

In [30]:
n_components = 30
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)

print(x_test_pca.shape)
print(x_train_pca.shape)

p = Pipeline([('Normalizing',MinMaxScaler()),('MultinomialNB',MultinomialNB())])
p.fit(x_train_pca,y_train) 

train_pred = p.predict(x_train_pca)
test_pred = p.predict(x_test_pca)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred,average='micro')}")
print(f"Train Recall: {recall_score(y_train,train_pred,average='micro')}")
print(f"Train F1 Score: {f1_score(y_train,train_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred,average='micro')}")
print(f"Test Recall: {recall_score(y_test,test_pred,average='micro')}")
print(f"Test F1 Score: {f1_score(y_test,test_pred,average='micro')}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))

(10000, 30)
(60000, 30)
*****SVC
Train Precision: 0.8713833333333333
Train Recall: 0.8713833333333333
Train F1 Score: 0.8713833333333333
Confusion Matrix:
[[600 247   6  76  32   2   5  10  20   2]
 [ 12 792   6 115  24  25   3   2  17   4]
 [  7   2 943  18   5  23   1   0   1   0]
 [  4   6   1 777  70  25  15 102   0   0]
 [  0   1   0  62 863  29   5   6  25   9]
 [  0   5  10  22 213 708  11  19   8   4]
 [  2   3  10  43  28  43 813  45   0  13]
 [  8   7   3 110  60   3 171 633   0   5]
 [119  34  10   5   7   8  13   1 780  23]
 [ 13  36   0  23  47   0  30  11  75 765]]
Test Data
Test Precision: 0.7674
Test Recall: 0.7674
Test F1 Score: 0.7674
Confusion Matrix:
[[600 247   6  76  32   2   5  10  20   2]
 [ 12 792   6 115  24  25   3   2  17   4]
 [  7   2 943  18   5  23   1   0   1   0]
 [  4   6   1 777  70  25  15 102   0   0]
 [  0   1   0  62 863  29   5   6  25   9]
 [  0   5  10  22 213 708  11  19   8   4]
 [  2   3  10  43  28  43 813  45   0  13]
 [  8   7   3 110  6