In [2]:
import pandas as pd

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])
df


Toxicity                                              tweet
0             0   @user when a father is dysfunctional and is s...
1             0  @user @user thanks for #lyft credit i can't us...
2             0                                bihday your majesty
3             0  #model   i love u take with u all the time in ...
4             0             factsguide: society now    #motivation
...         ...                                                ...
56740         1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
56741         1  you've gone and broke the wrong heart baby, an...
56742         1  young buck wanna eat!!.. dat nigguh like I ain...
56743         1              youu got wild bitches tellin you lies
56744         0  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[56745 rows x 2 columns]

In [3]:
def clean_text(texts):
    clean_texts = []
    for text in texts:
        text = text.lower()
        tokens = word_tokenize(text)
        cleaned_tokens = []
        lemmatizer = WordNetLemmatizer()
        for word in tokens:
            if (word.isalnum()) and (not word.isdigit()) and (word not in stop_words):
                word = word.strip(string.punctuation)
                word = lemmatizer.lemmatize(word)
                word = word.strip()
                cleaned_tokens.append(word)
            cleaned_text = " ".join(cleaned_tokens)
        clean_texts.append(cleaned_text)
        
    return clean_texts

In [4]:
clean_text(df['tweet'].values)

['user father dysfunctional selfish drag kid dysfunction run',
 'user user thanks lyft credit ca use cause offer wheelchair van pdx disapointed getthanked',
 'bihday majesty',
 'model love u take u time',
 'factsguide society motivation',
 'huge fan fare big talking leave chaos pay dispute get allshowandnogo',
 'user camping tomorrow user user user user user user user',
 'next school year year ca think school exam hate imagine actorslife revolutionschool girl',
 'love land allin cavs champion cleveland clevelandcavaliers',
 'user user welcome gr8',
 'ireland consumer price index mom climbed previous may blog silver gold forex',
 'selfish orlando standwithorlando pulseshooting orlandoshooting biggerproblems selfish heabreaking value love',
 'get see daddy today 80days gettingfed',
 'user cnn call michigan middle school wall chant tcot',
 'comment australia opkillingbay seashepherd helpcovedolphins thecove helpcovedolphins',
 'ouch junior got7 junior yugyoem omg',
 'thankful paner thankf

In [33]:
df['corpus'] = clean_text(df['tweet'].values)
#model= CountVectorizer()
model.fit(df['corpus'].values)
x=model.fit_transform(df['corpus'].values)
x

#X = data.drop(columns=['Toxicity'],axis=1)
#y = data['n_tweet']
#x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2)



<56745x52798 sparse matrix of type '<class 'numpy.int64'>'
	with 436406 stored elements in Compressed Sparse Row format>

In [35]:
#x.toarray()

df.head()

Toxicity                                              tweet  \
0         0   @user when a father is dysfunctional and is s...   
1         0  @user @user thanks for #lyft credit i can't us...   
2         0                                bihday your majesty   
3         0  #model   i love u take with u all the time in ...   
4         0             factsguide: society now    #motivation   

                                              corpus  
0  user father dysfunctional selfish drag kid dys...  
1  user user thanks lyft credit ca use cause offe...  
2                                     bihday majesty  
3                           model love u take u time  
4                      factsguide society motivation

In [48]:
model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = corpus
data

007beardownjedi  \
user father dysfunctional selfish drag kid dysf...                0   
user user thanks lyft credit ca use cause offer...                0   
bihday majesty                                                    0   
model love u take u time                                          0   
factsguide society motivation                                     0   
...                                                             ...   
muthaf lie lifeasking right tl trash mine bible...                0   
gone broke wrong heart baby drove redneck crazy                   0   
young buck wan na eat dat nigguh like aint fuck...                0   
youu got wild bitch tellin lie                                    0   
ntac eileen dahlia beautiful color combination ...                0   

                                                    007hertzrumble  00h30  \
user father dysfunctional selfish drag kid dysf...               0      0   
user user thanks lyft credit ca use cause offer...               0      0   
bihday majesty                                                   0      0   
model love u take u time                                         0      0   
factsguide society motivation                                    0      0   
...                                                            ...    ...   
muthaf lie lifeasking right tl trash mine bible...               0      0   
gone broke wrong heart baby drove redneck crazy                  0      0   
young buck wan na eat dat nigguh like aint fuck...               0      0   
youu got wild bitch tellin lie                                   0      0   
ntac eileen dahlia beautiful color combination ...               0      0   

                                                    00sexilexi00  0124jessi  \
user father dysfunctional selfish drag kid dysf...             0          0   
user user thanks lyft credit ca use cause offer...             0          0   
bihday majesty                                                 0          0   
model love u take u time                                       0          0   
factsguide society motivation                                  0          0   
...                                                          ...        ...   
muthaf lie lifeasking right tl trash mine bible...             0          0   
gone broke wrong heart baby drove redneck crazy                0          0   
young buck wan na eat dat nigguh like aint fuck...             0          0   
youu got wild bitch tellin lie                                 0          0   
ntac eileen dahlia beautiful color combination ...             0          0   

                                                    01takesthelead  \
user father dysfunctional selfish drag kid dysf...               0   
user user thanks lyft credit ca use cause offer...               0   
bihday majesty                                                   0   
model love u take u time                                         0   
factsguide society motivation                                    0   
...                                                            ...   
muthaf lie lifeasking right tl trash mine bible...               0   
gone broke wrong heart baby drove redneck crazy                  0   
young buck wan na eat dat nigguh like aint fuck...               0   
youu got wild bitch tellin lie                                   0   
ntac eileen dahlia beautiful color combination ...               0   

                                                    05235fd083ad408  \
user father dysfunctional selfish drag kid dysf...                0   
user user thanks lyft credit ca use cause offer...                0   
bihday majesty                                                    0   
model love u take u time                                          0   
factsguide society motivation                                     0   
...                                                       

In [19]:
# TFIDF------KNeighborsClassifier
from sklearn.metrics import confusion_matrix

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=KNeighborsClassifier(n_neighbors=2)

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****KNeighborsClassifier
Train Precision: 0.9714817110973342
Train Recall: 0.3249688925756947
Train F1 Score: 0.487024087024087
Test Data
Test Precision: 0.9164149043303121
Test Recall: 0.18705035971223022
Test F1 Score: 0.3106862410378969
Confusion Matrix:
[[6401   83]
 [3955  910]]


In [20]:
# TFIDF------DecisionTreeClassifier

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=DecisionTreeClassifier(criterion="entropy",max_depth=3,min_samples_split=10)

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****DecisionTreeClassifier
Train Precision: 0.9934396216339919
Train Recall: 0.6734060706344692
Train F1 Score: 0.8026997041420119
Test Data
Test Precision: 0.9944700460829493
Test Recall: 0.6724137931034483
Test F1 Score: 0.8023299045730574
Confusion Matrix:
[[6517   18]
 [1577 3237]]


In [13]:
# TFIDF------RandomForestClassifier
from sklearn.metrics import confusion_matrix

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=RandomForestClassifier()

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****RandomForestClassifier
Train Precision: 0.9998961632314003
Train Recall: 0.9991180742892717
Train F1 Score: 0.9995069673300984
Test Data
Test Precision: 0.9398274773827057
Test Recall: 0.9159319253639533
Test F1 Score: 0.9277258566978193
Confusion Matrix:
[[6186  286]
 [ 410 4467]]


In [14]:
# TFIDF------SVC
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=LinearSVC()

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****LinearSVC
Train Precision: 0.9922081969767804
Train Recall: 0.9859598410158468
Train F1 Score: 0.9890741507870754
Test Data
Test Precision: 0.952557127312296
Test Recall: 0.9156903765690376
Test F1 Score: 0.93376
Confusion Matrix:
[[6351  218]
 [ 403 4377]]


In [24]:
# TFIDF------NaiveBayes -- MultinomialNB

from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=MultinomialNB()

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))


*****MultinomialNB
Train Precision: 0.9409227891509924
Train Recall: 0.9388252371818134
Train F1 Score: 0.9398728428701181
Test Data
Test Precision: 0.8990472329211433
Test Recall: 0.9118009868421053
Test F1 Score: 0.9053791977135858
Confusion Matrix:
[[5987  498]
 [ 429 4435]]


In [25]:
# CountVectorizer------KNeighborsClassifier
from sklearn.metrics import confusion_matrix

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= CountVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=KNeighborsClassifier(n_neighbors=2)

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****KNeighborsClassifier
Train Precision: 0.9998164464023495
Train Recall: 0.8472546274692798
Train F1 Score: 0.9172349920013472
Test Data
Test Precision: 0.9593271403464725
Test Recall: 0.7852445540484998
Test F1 Score: 0.86360040682563
Confusion Matrix:
[[6321  162]
 [1045 3821]]


In [26]:
# CountVectorizer------DecisionTreeClassifier

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= CountVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=DecisionTreeClassifier(criterion="entropy",max_depth=3,min_samples_split=10)

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****DecisionTreeClassifier
Train Precision: 0.9937198437619668
Train Recall: 0.6730819110857499
Train F1 Score: 0.8025607719428466
Test Data
Test Precision: 0.9930492595950439
Test Recall: 0.6739130434782609
Test F1 Score: 0.8029321930360416
Confusion Matrix:
[[6450   23]
 [1590 3286]]


In [29]:
# CountVectorizer------RandomForestClassifier
from sklearn.metrics import confusion_matrix

df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= CountVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=RandomForestClassifier()

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




*****RandomForestClassifier
Train Precision: 0.999792412683585
Train Recall: 0.9992219917012448
Train F1 Score: 0.9995071208072842
Test Data
Test Precision: 0.9394904458598726
Test Recall: 0.9080648471167658
Test F1 Score: 0.9235103829698424
Confusion Matrix:
[[6191  285]
 [ 448 4425]]


In [27]:
# CountVectorizer------SVC
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= CountVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

model=LinearSVC()

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))




C:\Users\Suma Reddy\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\svm\_base.py:1235: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


*****LinearSVC
Train Precision: 0.9960587045584194
Train Recall: 0.9935340368301262
Train F1 Score: 0.9947947688722
Test Data
Test Precision: 0.936684896928902
Test Recall: 0.9236672889442025
Test F1 Score: 0.9301305483028721
Confusion Matrix:
[[6227  301]
 [ 368 4453]]


In [28]:
# CountVectorizer------NaiveBayes -- MultinomialNB

from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= CountVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = df['corpus']

X=data
y=df['Toxicity']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.1) 

model=MultinomialNB()

model.fit(x_train,y_train)
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

print(f"*****{type(model).__name__}")
print(f"Train Precision: {precision_score(y_train,train_pred)}")
print(f"Train Recall: {recall_score(y_train,train_pred)}")
print(f"Train F1 Score: {f1_score(y_train,train_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))
print("Test Data")
print(f"Test Precision: {precision_score(y_test,test_pred)}")
print(f"Test Recall: {recall_score(y_test,test_pred)}")
print(f"Test F1 Score: {f1_score(y_test,test_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,test_pred))


*****MultinomialNB
Train Precision: 0.9158697280860253
Train Recall: 0.956946171202284
Train F1 Score: 0.935957485137813
Test Data
Test Precision: 0.8828064764841943
Test Recall: 0.9400656814449918
Test F1 Score: 0.9105367793240556
Confusion Matrix:
[[2935  304]
 [ 146 2290]]


In [56]:
import nltk
#nltk.download('stopwords')
#nltk.download('punkt')
#nltk.download('punkt_tab')
#nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import string
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score,recall_score,f1_score


stop_words=set(stopwords.words('english'))


def clean_text(texts):
    clean_texts=[]
    for text in texts:
        text=text.lower()
        #print(text)
        tokens=word_tokenize(text)
        #print(tokens)
        cleaned_tokens=[]
        lemmatizer=WordNetLemmatizer()
        for word in tokens:
            if (word.isalnum()) and (not word.isdigit()) and (word not  in stop_words) :
                word=word.strip(string.punctuation)
                word=lemmatizer.lemmatize(word)
                word=word.strip()
                cleaned_tokens.append(word)
            cleaned_text=" ".join(cleaned_tokens)
        clean_texts.append(cleaned_text)
    return clean_texts


df = pd.read_csv("E:/DataScience/FinalBalancedDataset.csv")
df=df.drop(columns=['Unnamed: 0'])

df['corpus'] = clean_text(df['tweet'].values)

model= TfidfVectorizer(stop_words='english')
x=model.fit_transform(df['corpus'].values)
data = pd.DataFrame.sparse.from_spmatrix(x,columns=model.get_feature_names_out())
data.index = corpus

X=data
y=df['Toxicity']


x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2) 

models=[ KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),SVC() 
       ]
for model in models:

    model.fit(x_train,y_train)
    train_pred=model.predict(x_train)
    test_pred=model.predict(x_test)
    
    print(f"*****{type(model).__name__}")
    print(f"Train Precision: {precision_score(y_train,train_pred)}")
    print(f"Train Recall: {recall_score(y_train,train_pred)}")
    print(f"Train F1 Score: {f1_score(y_train,train_pred)}"/n)
    print("Test Data")
    print(f"Test Precision: {precision_score(y_test,test_pred)}")
    print(f"Test Recall: {recall_score(y_test,test_pred)}")
    print(f"Test F1 Score: {f1_score(y_test,test_pred)}"/n)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,test_pred))


*****KNeighborsClassifier
Train Precision: 0.9524434240734667
Train Recall: 0.30031023784901756
Train F1 Score: 0.4566396729302618/n
Test Data
Test Precision: 0.8665966386554622
Test Recall: 0.17141076251817994
Test F1 Score: 0.2862098872506505/n
Confusion Matrix:
[[6409  127]
 [3988  825]]
*****DecisionTreeClassifier
Train Precision: 0.9998965071151358
Train Recall: 0.9991209927611169
Train F1 Score: 0.9995085995085995/n
Test Data
Test Precision: 0.927010396774878
Test Recall: 0.9077498441720341
Test F1 Score: 0.9172790258240605/n
Confusion Matrix:
[[6192  344]
 [ 444 4369]]
*****RandomForestClassifier
Train Precision: 0.9997930570645145
Train Recall: 0.999224405377456
Train F1 Score: 0.9995086503400656/n
Test Data
Test Precision: 0.9428205675272029
Test Recall: 0.918138375233742
Test F1 Score: 0.9303157894736842/n
Confusion Matrix:
[[6268  268]
 [ 394 4419]]


AttributeError: 'csr_matrix' object has no attribute 'var'